"""empty message

Revision ID: 09d92779e4c7
Revises: 66c76073f8a7
Create Date: 2018-05-07 11:10:00.491186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d92779e4c7'
down_revision = '66c76073f8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_id', sa.INTEGER(), nullable=True),
    sa.Column('payment', sa.NUMERIC(), nullable=True),
    sa.Column('penalty', sa.INTEGER(), nullable=True),
    sa.Column('scheduled_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('paid', sa.INTEGER(), nullable=True),
    sa.Column('paid_by_borrower', sa.INTEGER(), nullable=True),
    sa.Column('paid_by_guarantor', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
