"""empty message

Revision ID: 0de4a3c44359
Revises: 6241e2f07921
Create Date: 2018-03-21 20:34:31.698006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de4a3c44359'
down_revision = '6241e2f07921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'last_update')
    # ### end Alembic commands ###
