"""empty message

Revision ID: 66c76073f8a7
Revises: da1bf5f4f14e
Create Date: 2018-05-06 19:35:56.288025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c76073f8a7'
down_revision = 'da1bf5f4f14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'name')
    # ### end Alembic commands ###
