"""empty message

Revision ID: 74a2256b1e7e
Revises: f194abc223d5
Create Date: 2018-05-07 12:27:51.955892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a2256b1e7e'
down_revision = 'f194abc223d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('interest_pmt', sa.Numeric(), nullable=True))
    op.add_column('payments', sa.Column('principal_pmt', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'principal_pmt')
    op.drop_column('payments', 'interest_pmt')
    # ### end Alembic commands ###
